export function buildStartMessage(): string {
  return [
    '👋 <b>Привет!</b>',
    'Я помогу подобрать маршрут свопа и провести его через доступных агрегаторов.',
    'ℹ️ Полная справка по возможностям: <code>/help</code>',
  ].join('\n');
}

export function buildHelpMessage(): string {
  return [
    'ℹ️ <b>Справка по боту</b>',
    '',
    '<b>1. Котировки</b>',
    '<code>/price &lt;amount&gt; &lt;from&gt; to &lt;to&gt; [on &lt;chain&gt;]</code>',
    'Примеры:',
    '<code>/price 10 ETH to USDC</code>',
    '<code>/price 100 USDC to WETH on base</code>',
    '<code>/price 1 SOL to USDC on solana</code>',
    '',
    '<b>2. Свопы</b>',
    '<code>/swap &lt;amount&gt; &lt;from&gt; to &lt;to&gt; [on &lt;chain&gt;]</code>',
    'После команды бот покажет агрегаторов, gross, комиссию бота и net, а затем даст выбрать маршрут кнопкой.',
    'Примеры:',
    '<code>/swap 0.1 ETH to USDC</code>',
    '<code>/swap 0.1 ETH to USDC on arbitrum</code>',
    '<code>/swap 1 SOL to USDC on solana</code>',
    '',
    '<b>3. Approve</b>',
    '<code>/approve &lt;amount&gt; &lt;token&gt; [on &lt;chain&gt;]</code>',
    'Показывает spender для EVM-агрегаторов и даёт выбрать approve exact или approve max.',
    '<code>/approve 100 USDC on arbitrum</code>',
    '',
    '<b>4. Адрес токена вместо символа</b>',
    'Если указываешь адрес токена, сеть обязательна.',
    '<code>/price 100 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 to USDT on ethereum</code>',
    '<code>/swap 1 SOL to EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v on solana</code>',
    '',
    '<b>5. Кошелёк</b>',
    '<code>/connect [on &lt;chain&gt;]</code>',
    '<code>/disconnect [on &lt;chain&gt;]</code>',
    'EVM-подключение общее для <code>ethereum</code>, <code>arbitrum</code>, <code>base</code> и <code>optimism</code>.',
    '',
    '<b>6. Портфель</b>',
    '<code>/portfolio</code> — балансы подключённых кошельков по всем сетям.',
    '',
    '<b>7. Избранное и алерты</b>',
    '<code>/favorites</code> — сохранённые пары, текущий курс, установка алерта, удаление.',
    'Кнопки после <code>/price</code> и <code>/swap</code>: ⭐ В избранное, 🔔 Алерт.',
    'Алерт одноразовый: срабатывает, когда лучший net пересекает заданный порог вверх или вниз.',
    '',
    '<b>8. Пресеты</b>',
    '<code>/templates</code> — сохранённые торговые пресеты.',
    'Кнопка «Сохранить как пресет» доступна после <code>/price</code> и <code>/swap</code>.',
    '',
    '<b>9. История</b>',
    '<code>/history</code> — последние успешные обмены.',
    '',
    '<b>10. Статус транзакции</b>',
    '<code>/tx &lt;hash&gt;</code> — проверить статус транзакции по хешу.',
    '',
    '<b>11. Настройки</b>',
    '<code>/settings</code> — slippage и предпочитаемый агрегатор.',
    '',
    '<b>Поддерживаемые сети</b>',
    '<code>ethereum</code>, <code>arbitrum</code>, <code>base</code>, <code>optimism</code>, <code>solana</code>',
  ].join('\n');
}
