export const ENV_KEY_NODE_ENV = 'NODE_ENV';
export const ENV_KEY_PORT = 'PORT';
export const ENV_KEY_DATABASE_URL = 'DATABASE_URL';
export const ENV_KEY_TELEGRAM_ENABLED = 'TELEGRAM_ENABLED';
export const ENV_KEY_TELEGRAM_BOT_TOKEN = 'TELEGRAM_BOT_TOKEN';
export const ENV_KEY_METRICS_ENABLED = 'METRICS_ENABLED';
export const ENV_KEY_CACHE_TTL_PRICE = 'CACHE_TTL_PRICE';
export const ENV_KEY_WC_PROJECT_ID = 'WC_PROJECT_ID';
export const ENV_KEY_APP_PUBLIC_URL = 'APP_PUBLIC_URL';
export const ENV_KEY_SWAP_SLIPPAGE = 'SWAP_SLIPPAGE';
export const ENV_KEY_SWAP_TIMEOUT_SECONDS = 'SWAP_TIMEOUT_SECONDS';
export const ENV_KEY_WALLET_CONNECT_SESSION_TTL_SEC = 'WALLET_CONNECT_SESSION_TTL_SEC';
export const ENV_KEY_TELEGRAM_PENDING_ACTION_TTL_SEC = 'TELEGRAM_PENDING_ACTION_TTL_SEC';
export const ENV_KEY_PRICE_ALERTS_POLL_INTERVAL_SEC = 'PRICE_ALERTS_POLL_INTERVAL_SEC';
export const ENV_KEY_MAX_ACTIVE_PRICE_ALERTS_PER_USER = 'MAX_ACTIVE_PRICE_ALERTS_PER_USER';
export const ENV_KEY_COINGECKO_API_BASE_URL = 'COINGECKO_API_BASE_URL';
export const ENV_KEY_ZEROX_FEE_BPS = 'ZEROX_FEE_BPS';
export const ENV_KEY_ZEROX_FEE_RECIPIENT = 'ZEROX_FEE_RECIPIENT';
export const ENV_KEY_ZEROX_FEE_TOKEN_MODE = 'ZEROX_FEE_TOKEN_MODE';
export const ENV_KEY_PARASWAP_FEE_BPS = 'PARASWAP_FEE_BPS';
export const ENV_KEY_PARASWAP_PARTNER_ADDRESS = 'PARASWAP_PARTNER_ADDRESS';
export const ENV_KEY_PARASWAP_API_VERSION = 'PARASWAP_API_VERSION';
export const ENV_KEY_JUPITER_PLATFORM_FEE_BPS = 'JUPITER_PLATFORM_FEE_BPS';
export const ENV_KEY_ODOS_MONETIZATION_MODE = 'ODOS_MONETIZATION_MODE';
export const ENV_KEY_ODOS_REFERRAL_CODE = 'ODOS_REFERRAL_CODE';
export const ENV_KEY_ODOS_MONETIZED_CHAINS = 'ODOS_MONETIZED_CHAINS';
export const ENV_KEY_TX_TRACKING_ENABLED = 'TX_TRACKING_ENABLED';
export const ENV_KEY_TX_TRACKING_POLL_INTERVAL_SEC = 'TX_TRACKING_POLL_INTERVAL_SEC';
export const ENV_KEY_TX_TRACKING_TIMEOUT_SEC = 'TX_TRACKING_TIMEOUT_SEC';

export const MIN_PORT = 1;
export const MAX_PORT = 65_535;
export const MIN_CACHE_TTL = 1;
export const MIN_SWAP_TIMEOUT_SECONDS = 1;
export const MIN_SLIPPAGE = 0;
export const MIN_FEE_BPS = 0;
export const MAX_FEE_BPS = 10_000;
export const MAX_PARASWAP_FEE_BPS = 200;

export const DEFAULT_CACHE_TTL_PRICE = 30;
export const DEFAULT_SWAP_TIMEOUT_SECONDS = 300;
export const DEFAULT_SWAP_SLIPPAGE = 0.5;
export const DEFAULT_WALLET_CONNECT_SESSION_TTL_SECONDS = 604800;
export const DEFAULT_TELEGRAM_PENDING_ACTION_TTL_SECONDS = 300;
export const DEFAULT_MAX_ACTIVE_PRICE_ALERTS_PER_USER = 20;
export const DEFAULT_PRICE_ALERTS_POLL_INTERVAL = 60;
export const DEFAULT_TX_TRACKING_POLL_INTERVAL = 15;
export const DEFAULT_TX_TRACKING_TIMEOUT = 600;
export const MIN_TX_TRACKING_POLL_INTERVAL = 5;
export const MIN_TX_TRACKING_TIMEOUT = 60;
export const PARASWAP_SUPPORTED_API_VERSION = '6.2';

export const ALLOWED_ZEROX_FEE_TOKEN_MODES = ['auto', 'buy', 'sell'] as const;
export const ALLOWED_ODOS_MONETIZATION_MODES = ['disabled', 'tracking_only', 'enforced'] as const;
export const ALLOWED_ODOS_MONETIZED_CHAINS = ['ethereum', 'arbitrum', 'base', 'optimism'] as const;
export const JUPITER_FEE_ACCOUNT_KEYS = [
  'JUPITER_FEE_ACCOUNT_SOL',
  'JUPITER_FEE_ACCOUNT_USDC',
  'JUPITER_FEE_ACCOUNT_USDT',
  'JUPITER_FEE_ACCOUNT_JUP',
  'JUPITER_FEE_ACCOUNT_BONK',
] as const;
export const ALLOWED_NODE_ENVS = ['development', 'production', 'test'] as const;

export type NodeEnvironment = (typeof ALLOWED_NODE_ENVS)[number];
export type EnvironmentSource = Record<string, unknown>;
export type EnvironmentResult = Record<string, unknown>;
